version: '2'
services:
  jhtemplatefinder-app:
    image: jhtemplatefinder
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jhtemplatefinder-postgresql:5432/jhtemplatefinder
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 12345:12345
  jhtemplatefinder-postgresql:
    extends:
      file: postgresql.yml
      service: jhtemplatefinder-postgresql
